name       : haskell-gio
version    : 0.13.3.1
release    : 1
source     :
    - http://hackage.haskell.org/package/gio-0.13.3.1/gio-0.13.3.1.tar.gz : ac63f42321800731b9dc1f753f27ee877c04fdf7bcbcab0e2c57348a4739d827
license    : LGPL-2.1
component  : programming.haskell
summary    : GIO is striving to provide a modern, easy-to-use VFS API that sits at the right level in the library stack. The goal is to overcome the shortcomings of GnomeVFS and provide an API that is so good that developers prefer it over raw POSIX calls. Among other things that means using GObject. It also means not cloning the POSIX API, but providing higher-level, document-centric interfaces.
description: |
    GIO is striving to provide a modern, easy-to-use VFS API that sits at the right level in the library stack. The goal is to overcome the shortcomings of GnomeVFS and provide an API that is so good that developers prefer it over raw POSIX calls. Among other things that means using GObject. It also means not cloning the POSIX API, but providing higher-level, document-centric interfaces.
builddeps  :
    - pkgconfig(gobject-introspection-1.0)
    - ghc-devel
    - gtk2hs-buildtools-devel
    - haskell-cabal-install
    - haskell-glib
    - haskell-hashable-devel
    - haskell-hashtables-devel
    - haskell-primitive-devel
    - haskell-random-devel
    - haskell-text-devel
    - haskell-vector-devel
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
