name       : haskell-gio
version    : 0.13.5.0
release    : 4
source     :
    - https://hackage.haskell.org/package/gio-0.13.5.0/gio-0.13.5.0.tar.gz : 5c761423e947c02181721bdac7c11293d1bd31515fabe969e7e4ac9fd7e7355c
license    : LGPL-2.1
component  : programming.haskell
summary    : GIO is striving to provide a modern, easy-to-use VFS API that sits at
    the right level in the library stack. The goal is to overcome the shortcomings
    of GnomeVFS and provide an API that is so good that developers prefer it over
    raw POSIX calls. Among other things that means using GObject. It also means not
    cloning the POSIX API, but providing higher-level, document-centric interfaces.
description: |
    GIO is striving to provide a modern, easy-to-use VFS API that sits at the right level in the library stack. The goal is to overcome the shortcomings of GnomeVFS and provide an API that is so good that developers prefer it over raw POSIX calls. Among other things that means using GObject. It also means not cloning the POSIX API, but providing higher-level, document-centric interfaces.
builddeps  :
    - pkgconfig(gobject-introspection-1.0)
    - ghc-devel
    - gtk2hs-buildtools-devel
    - haskell-cabal-install
    - haskell-glib
    - haskell-hashable-devel
    - haskell-hashtables-devel
    - haskell-mtl
    - haskell-primitive-devel
    - haskell-random-devel
    - haskell-text-devel
    - haskell-vector-devel
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
